# Generated by Django 3.1.2 on 2020-10-11 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodiItem',
            new_name='TodoItem',
        ),
    ]
